name = "TestPkg"
uuid = "d629ae56-6bdb-4cc2-a66c-4b8884e41333"
authors = ["Franco Tavella"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
DifferentialEquations = "7"
julia = "1.1"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
